dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit_learn
    - matplotlib
    - pandas
    - thinc
    - tqdm
    - sklearn
    - Pillow
    - xgboost
    - sympy
    - requests
    - lightgbm
    - catboost
